ROUTINE MasterLib.Utils.DynamicObject.Adapter [Type=INC]

 #define LogicalToXSDMethodName						"LogicalToXSD"
 #define MethodDoesNotExistErrorPrefix				"<METHOD DOES NOT EXIST>"
 #define DataTypeAssignmentMode						1
 #define SerialObjectAssignmentMode					2
 #define PersistentObjectAssignmentMode				3
 #define ArrayOfDTAssignmentMode					4
 #define ArrayOfObjectsPersistantAssignmentMode		5
 #define ArrayOfObjectsNonPersistantAssignmentMode	6
 #define ListOfDTAssignmentMode						7
 #define ListOfObjectsPersistantAssignmentMode		8
 #define ListOfObjectsNonPersistantAssignmentMode	9
 #define EmbededRegisteredObjectAssignmentMode		10
 #define UnsupportedMode							""
 #define NewLine									$CHAR(13,10)
 #define DynamicObjReferenceName					"pDynamicObject"
 #define XSDToLogicalMethodName						"XSDToLogical"
 #define ReferenceIsNotADynamicObject				"5002"
 #define DynamicJSONArrayProjection						"jsonarray"
 #define DynamicNativeProjection					"native"
 #define ArrayDynamicObjectProjectionModeParameter	"ArrayDynamicObjectMode"
